In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from tqdm import tqdm
import json

In [2]:
df = pd.read_json('/21_hf216/project/flask/model/embedding.json', orient='index', convert_axes=False)
df.index = df.index.astype(int)
df

isbn                                              title  \
0     9771197225987                                     흘러가는 구름을 동경하였다   
1     9772586200006                            장애와 테크놀로지 - 과학잡지 에피 16호   
2     9772586200211                               식물의 과학 - 과학잡지 에피 17호   
3     9772733807003                       에픽 #04 - BELOVED, 2021.7.8.9   
4     9772765656006                            오늘의 좋은 소설 2021.가을 - 58호   
...             ...                                                ...   
5901  9791197556609                                          왓더? 오디오 1   
5902  9791197558009      오늘의 어린이책 1 - 다움북클럽이 고른 성평등 어린이·청소년책 2019-2021   
5903  9791197559105  괜찮아, 아빠도 쉽진 않더라 - 오늘을 살아가는 우리 모두를 위한 동화, &lt;퇴...   
5904  9791197566400                                       미래를 향한 노스탤지어   
5905  9791197578410          채사장의 지대넓얕 1 : 권력의 탄생 - 지적 대화를 위한 넓고 얕은 지식   

                                                 author  \
0           김시탁, 김일태, 민창홍, 성선경, 이강휘, 이기영, 이달균, 이서린, 이월춘   
1     김초엽, 김원영, 김상희, 유기훈, 이주현, 류성두, 명수민, 킴 포춘, 전치형, ...   
2     강연실, 허준이, 금종해, 안수지, 이상엽, 남재환, 황승식, 장진성, 박찬열, 강...   
3     임현, 임철홍, 에밀리 정민 윤, 이정식, 임소라, 김대성, 박하빈, 염은영, 김혜...   
4                                김현, 서정아, 이미욱, 이태형, 정미형   
...                                                 ...   
5901                                최윤욱, 김연승, 최창림 (디자인)   
5902                                             다움북클럽    
5903                                                문수림   
5904                                                신미로   
5905                                     채사장, 마케마케, 정용환   

                                            description  \
0     시문학연구회 하로동선의 여섯 번째 동인지 지금까지 현대시의 새로운 방향성을 탐구해 ...   
1     에피 16호 키워드 숨 섹션은 장애와 테크놀로지를 주제로 삼았다 기술의 발전이 장애...   
2     과학비평 계간지 에피 17호는 식물의 과학을 다루며 17편의 글을 담았다 식물을 나...   
3     4호의 제호는 이다 1988년 퓰리처상 수상작이기도 한 토니 모리슨의 장편 빌러비드...   
4     오늘의 좋은 소설은 간단하다 무겁지도 어렵지도 않다 어떤 장식과 해설도 하지 않고 ...   
...                                                 ...   
5901  만화는 여주인공인 수진이가 이어폰으로 음악을 듣다가 귀에 이명이 와서 스피커를 통해...   
5902  다시 시작하는 다움북클럽이 고른 성평등 어린이청소년책 목록 20192021은 기존 ...   
5903  여기 마흔 한 살에 아빠가 된 무명 작가가 있다 대중에게 인식되지 못할 정도의 글솜...   
5904  불길한 죽음의 예감 때문에 시작된 여행 그 수많은 여행에서 내가 가장 멀리까지 가본...   
5905  인문학 분야 트리플 밀리언셀러 지적 대화를 위한 넓고 얕은 지식의 핵심 주제를 스토...   

                                              embedding  
0     [0.0204815902, -0.0246927589, 0.0121974256, -0...  
1     [0.053946472700000005, 0.0389155485, -0.065167...  
2     [0.0425348282, -0.001016365, 0.0275022946, -0....  
3     [-0.0164510403, -0.0326857828, -0.030496580500...  
4     [-0.0835911483, -0.0344673805, -0.0317332558, ...  
...                                                 ...  
5901  [0.0143019306, 0.065724805, -0.073053017300000...  
5902  [0.039877310400000004, 0.059916768200000005, -...  
5903  [0.0164277442, 0.022679476100000002, -0.062934...  
5904  [0.024699792300000002, 0.0388688855, 0.0501790...  
5905  [-0.0161138847, -0.010394363700000001, -0.0335...  

[5906 rows x 5 columns]

In [3]:
array_embedding = np.array([np.array(xi) for xi in df['embedding']])
array_embedding

print(array_embedding)
print(array_embedding.shape)

[[ 0.02048159 -0.02469276  0.01219743 ... -0.00748555  0.04424235
  -0.03050543]
 [ 0.05394647  0.03891555 -0.06516731 ...  0.02442932  0.00083294
   0.06470378]
 [ 0.04253483 -0.00101636  0.02750229 ...  0.02031231  0.0417028
   0.01048673]
 ...
 [ 0.01642774  0.02267948 -0.06293406 ... -0.0275322   0.01551969
  -0.01796406]
 [ 0.02469979  0.03886889  0.05017901 ... -0.05910482 -0.07302563
   0.054513  ]
 [-0.01611388 -0.01039436 -0.03350396 ...  0.01053391 -0.05075977
  -0.03108357]]
(5906, 512)


In [4]:
cosine_scores = cosine_similarity(array_embedding, array_embedding)
print(cosine_scores)
print(cosine_scores.shape)

[[1.         0.14435119 0.17866998 ... 0.0979716  0.1581726  0.19873812]
 [0.14435119 1.         0.26626256 ... 0.12936235 0.08925515 0.17847836]
 [0.17866998 0.26626256 1.         ... 0.15882839 0.14266748 0.18743441]
 ...
 [0.0979716  0.12936235 0.15882839 ... 1.         0.26299181 0.34600906]
 [0.1581726  0.08925515 0.14266748 ... 0.26299181 1.         0.12055084]
 [0.19873812 0.17847836 0.18743441 ... 0.34600906 0.12055084 1.        ]]
(5906, 5906)


In [5]:
# test printing
idx = np.argsort(-cosine_scores[0])[:10] # top 10의 인덱스 추출
idx = [x for x in idx if cosine_scores[0][x] < 0.99][:5] # 유사도가 1인것 빼고 5개 추출
print(idx)
print(cosine_scores[0][idx])
print(df.loc[0, ['title', 'description']])
print(df.loc[df.index.isin(idx), ['title', 'description']])

[2246, 5156, 4939, 5088, 4729]
[0.50740892 0.47227943 0.45533747 0.44046394 0.43540822]
title                                             흘러가는 구름을 동경하였다
description    시문학연구회 하로동선의 여섯 번째 동인지 지금까지 현대시의 새로운 방향성을 탐구해 ...
Name: 0, dtype: object
                                              title  \
2246                                   빨간 치마를 입은 아이   
4729             모든 이의 과학사 강의 - 역사와 문화로 이해하는 과학 인문학   
4939                        소비자행동 - 마케팅 전략적 접근, 제7판   
5088                                  삽화와 함께 읽는 도련님   
5156  회사는 싫지만 회사 생활은 잘하고 싶어 - 요즘 직장인을 위한 12가지 생존 기술   

                                            description  
2246  2018년 문화일보 신춘문예로 등단한 이경란의 첫 소설집  작가의 항해와 탐색은 관...  
4729  앎이 삶을 바꾼다는 관점에서 인간의 탄생에서 현대의 눈부신 과학기술의 발전과 그 명...  
4939  다른 모든 학문 분야와 마찬가지로 소비자행동에 관한 연구는 지속적으로 발전되고 있다...  
5088  일본의 대문호이자 현대문학의 개척자인 나쓰메 소세키의 대표작 도련님이 만화의 개척자...  
5156  신입부터 시작해 6년 만에 가 된 직장의 신 추이추이의 회사 생활 노하우를 모두 담...  


In [18]:
top_isbn = df.loc[df.index.isin(idx), 'isbn'].tolist()
print(top_isbn)
print(type(top_isbn))

[9788982182839, 9791187700364, 9791189295035, 9791190156226, 9791190312035]
<class 'list'>


In [22]:
def sort_cosine_score_top_n(n: int=5, threshold: int=0.95):
    df['top_isbn'] = 0
    df['cosine_similarity'] = 0
    df['top_isbn'] = df['top_isbn'].astype('object') # list 삽입 위해 object 자료형으로 변환
    df['cosine_similarity'] = df['cosine_similarity'].astype('object')
    for i, row in tqdm(enumerate(cosine_scores)):
        idx = np.argsort(-row)[:10] # top 10의 인덱스 추출
        idx = [x for x in idx if row[x] < threshold][:n] # 유사도가 0.99를 넘지 않는 인덱스 n개 추출
        df.at[i, 'top_isbn'] = df.loc[df.index.isin(idx), 'isbn'].tolist()
        df.at[i, 'cosine_similarity'] = row[idx]        

sort_cosine_score_top_n()
df.head()


5906it [00:02, 2033.79it/s]


isbn                         title  \
0  9771197225987                흘러가는 구름을 동경하였다   
1  9772586200006       장애와 테크놀로지 - 과학잡지 에피 16호   
2  9772586200211          식물의 과학 - 과학잡지 에피 17호   
3  9772733807003  에픽 #04 - BELOVED, 2021.7.8.9   
4  9772765656006       오늘의 좋은 소설 2021.가을 - 58호   

                                              author  \
0        김시탁, 김일태, 민창홍, 성선경, 이강휘, 이기영, 이달균, 이서린, 이월춘   
1  김초엽, 김원영, 김상희, 유기훈, 이주현, 류성두, 명수민, 킴 포춘, 전치형, ...   
2  강연실, 허준이, 금종해, 안수지, 이상엽, 남재환, 황승식, 장진성, 박찬열, 강...   
3  임현, 임철홍, 에밀리 정민 윤, 이정식, 임소라, 김대성, 박하빈, 염은영, 김혜...   
4                             김현, 서정아, 이미욱, 이태형, 정미형   

                                         description  \
0  시문학연구회 하로동선의 여섯 번째 동인지 지금까지 현대시의 새로운 방향성을 탐구해 ...   
1  에피 16호 키워드 숨 섹션은 장애와 테크놀로지를 주제로 삼았다 기술의 발전이 장애...   
2  과학비평 계간지 에피 17호는 식물의 과학을 다루며 17편의 글을 담았다 식물을 나...   
3  4호의 제호는 이다 1988년 퓰리처상 수상작이기도 한 토니 모리슨의 장편 빌러비드...   
4  오늘의 좋은 소설은 간단하다 무겁지도 어렵지도 않다 어떤 장식과 해설도 하지 않고 ...   

                                           embedding  \
0  [0.0204815902, -0.0246927589, 0.0121974256, -0...   
1  [0.053946472700000005, 0.0389155485, -0.065167...   
2  [0.0425348282, -0.001016365, 0.0275022946, -0....   
3  [-0.0164510403, -0.0326857828, -0.030496580500...   
4  [-0.0835911483, -0.0344673805, -0.0317332558, ...   

                                            top_isbn  \
0  [9788982182839, 9791187700364, 9791189295035, ...   
1  [9788932474397, 9788999714252, 9791156758693, ...   
2  [9788983715005, 9788997132898, 9791160074970, ...   
3  [9788925555225, 9788937460067, 9788954605908, ...   
4  [9788932038230, 9788932321530, 9788937473098, ...   

                                   cosine_similarity  
0  [0.5074089234027234, 0.47227943017468454, 0.45...  
1  [0.46987478014265105, 0.46203363517838786, 0.4...  
2  [0.5278332704913822, 0.5250382443039214, 0.522...  
3  [0.5193957943271292, 0.5152831362876995, 0.496...  
4  [0.615338607365047, 0.6122161907611396, 0.6040...

In [4]:
df.to_json('/21_hf216/project/flask/model/top_isbn_with_scores.json', orient='index', force_ascii=False, indent=4)
df.head(3)

In [1]:
import pandas as pd

In [2]:
df = pd.read_json('/21_hf216/project/flask/model/top_isbn_with_scores.json', orient='index', convert_axes=False)
df.to_csv('/21_hf216/project/flask/model/top_isbn_with_scores.csv', index=False, sep='|')

In [3]:
df = pd.read_csv('/21_hf216/project/flask/model/top_isbn_with_scores.json', sep='|')
df.head(3)

ParserError: Error tokenizing data. C error: Expected 1 fields in line 3, saw 2
